import { type NextPage } from "next";
import Carousel from "~/components/carousel";
import Head from "next/head";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto max-w-md">
        <h1 className="text-2xl font-semibold">Nico Daniels</h1>
        <Carousel />
      </main>

    </>
  );
};

export default Home;